spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/second_life
    username: vlad
    password: vlad
    platform: POSTGRESQL
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-secondlife.xml

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false

server:
  port: 8081
